name: Check
on:
    push:
        branches:
            - master
    pull_request:

defaults:
    run:
        working-directory: ./code

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4

            - run: npm install
            - run: npm run lint
